# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```


2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [33]:
a.sum()、sum(a)是相同的
但他們不能處理二維及二維以上的資料，
對於一維的資料，三者用處是相同的

sum() 是 python 內建的函式，所有型態皆可以用。
np.sum(a) 跟 a.sum() 是陣列專有的函式，
差別在於定義在 np 或是 array 底下。

SyntaxError: invalid character in identifier (<ipython-input-33-af2adcdb0f5e>, line 1)

In [9]:
import numpy as np
a=np.arange(6)
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 

15
15
15


In [13]:
b=np.arange(6).reshape(2,3)
print(b.sum()) 
print(b.sum())
print(sum(b)) 

15
15
[3 5 7]


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [22]:
# 記得先 Import 正確的套件

import numpy as np

In [23]:
A = np.random.random((5, 5))
A

array([[0.94922731, 0.65016772, 0.72722475, 0.78764598, 0.40890289],
       [0.10377042, 0.52629226, 0.15942393, 0.10181395, 0.11932276],
       [0.79011525, 0.65902739, 0.62861237, 0.56097996, 0.5207213 ],
       [0.70353195, 0.94488465, 0.05049835, 0.84898322, 0.51947218],
       [0.88377189, 0.18724082, 0.94761243, 0.65852654, 0.68092594]])

In [34]:
A = (A - A.min()) / (A.max() - A.min()) #分子減最小值除以最大值減最小值
A

array([[1.        , 0.66724162, 0.75298164, 0.82021128, 0.39879047],
       [0.0592749 , 0.52940757, 0.12119959, 0.05709797, 0.07657971],
       [0.82295879, 0.67709963, 0.64325737, 0.56800396, 0.52320885],
       [0.72661907, 0.995168  , 0.        , 0.88846015, 0.52181898],
       [0.9271689 , 0.15215096, 0.99820315, 0.67654234, 0.70146576]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [52]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
#np.where(c==np.max(c))

In [58]:
np.argmax(c)
c[9]=-1
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, -1])

In [47]:
Z = np.random.random(10)
Z[Z.argmax()] = -1
print (Z)

[ 0.29715321  0.1193656  -1.          0.49006413  0.11171403  0.60565972
  0.2406334   0.24122683  0.52593271  0.55993995]
